### ISSUE TITLE
Migration to Composer autoloading

### ISSUE THREAD

**Issue by kix** [TimeToogo/Penumbra#2]
As I see from the source, you're using your own autoload function. Why so, and wouldn't it be easier to use Composer/PSR-0 autoloading instead?

**Comment by TimeToogo** [comment]
The built in autoloader function is optional, this single file can be manually required if composer is not available. Otherwise penumbra will be loaded automatically according to PSR-4.

**Comment by kix** [comment]
@TimeToogo, that's great, thanks!
