### ISSUE TITLE
why the upper case in methods? discouraged me to try it

### ISSUE THREAD

**Issue by cordoval** [TimeToogo/Penumbra#6]

**Comment by TimeToogo** [comment]
I would not attempt to use this library as it currently stands (unfinished and unstable).
I am planning to rewrite this library based on V3 of PINQ after its release.
This will follow psr-2 coding guidelines and hence the standard method naming convention.

Thanks

**Comment by cordoval** [comment]
did not know PSR-2 allowed upper cases. In any case, let's start V3.
And as for "I would not attempt to use this library as it currently stands (unfinished and unstable)." is not for you to decide :blush: he he :+1: 
good job so far, let's hit the road with the new rewrite then!

**Comment by TimeToogo** [comment]
Just clarifying that PSR-2 does not permit upper case method names.
This library does not follow PSR-2 hence the strange method names.
I meant to say that when the library is rewritten, it will follow PSR-2.

**Comment by cordoval** [comment]
you are the man, thanks for the clarification. I don't know much but if you need help cleaning up or reviewing PRs please assign me rookie work. FOSS FTW!
